# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from weni.statistic_grpc.grpc_gen import statistic_pb2 as weni_dot_statistic__grpc_dot_grpc__gen_dot_statistic__pb2


class OrgStatisticControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
                '/weni.rapidpro.statistic.OrgStatisticController/Retrieve',
                request_serializer=weni_dot_statistic__grpc_dot_grpc__gen_dot_statistic__pb2.OrgStatisticRetrieveRequest.SerializeToString,
                response_deserializer=weni_dot_statistic__grpc_dot_grpc__gen_dot_statistic__pb2.OrgStatistic.FromString,
                )


class OrgStatisticControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrgStatisticControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=weni_dot_statistic__grpc_dot_grpc__gen_dot_statistic__pb2.OrgStatisticRetrieveRequest.FromString,
                    response_serializer=weni_dot_statistic__grpc_dot_grpc__gen_dot_statistic__pb2.OrgStatistic.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weni.rapidpro.statistic.OrgStatisticController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrgStatisticController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/weni.rapidpro.statistic.OrgStatisticController/Retrieve',
            weni_dot_statistic__grpc_dot_grpc__gen_dot_statistic__pb2.OrgStatisticRetrieveRequest.SerializeToString,
            weni_dot_statistic__grpc_dot_grpc__gen_dot_statistic__pb2.OrgStatistic.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
