# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weni/classifier_grpc/grpc_gen/classifier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="weni/classifier_grpc/grpc_gen/classifier.proto",
    package="classifier",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n.weni/classifier_grpc/grpc_gen/classifier.proto\x12\nclassifier")\n\x15\x43lassifierListRequest\x12\x10\n\x08org_uuid\x18\x01 \x01(\t"A\n\nClassifier\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x17\n\x0f\x63lassifier_type\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t2]\n\x14\x43lassifierController\x12\x45\n\x04List\x12!.classifier.ClassifierListRequest\x1a\x16.classifier.Classifier"\x00\x30\x01\x62\x06proto3',
)


_CLASSIFIERLISTREQUEST = _descriptor.Descriptor(
    name="ClassifierListRequest",
    full_name="classifier.ClassifierListRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="org_uuid",
            full_name="classifier.ClassifierListRequest.org_uuid",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=62,
    serialized_end=103,
)


_CLASSIFIER = _descriptor.Descriptor(
    name="Classifier",
    full_name="classifier.Classifier",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="uuid",
            full_name="classifier.Classifier.uuid",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="classifier_type",
            full_name="classifier.Classifier.classifier_type",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="name",
            full_name="classifier.Classifier.name",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=105,
    serialized_end=170,
)

DESCRIPTOR.message_types_by_name["ClassifierListRequest"] = _CLASSIFIERLISTREQUEST
DESCRIPTOR.message_types_by_name["Classifier"] = _CLASSIFIER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassifierListRequest = _reflection.GeneratedProtocolMessageType(
    "ClassifierListRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _CLASSIFIERLISTREQUEST,
        "__module__": "weni.classifier_grpc.grpc_gen.classifier_pb2"
        # @@protoc_insertion_point(class_scope:classifier.ClassifierListRequest)
    },
)
_sym_db.RegisterMessage(ClassifierListRequest)

Classifier = _reflection.GeneratedProtocolMessageType(
    "Classifier",
    (_message.Message,),
    {
        "DESCRIPTOR": _CLASSIFIER,
        "__module__": "weni.classifier_grpc.grpc_gen.classifier_pb2"
        # @@protoc_insertion_point(class_scope:classifier.Classifier)
    },
)
_sym_db.RegisterMessage(Classifier)


_CLASSIFIERCONTROLLER = _descriptor.ServiceDescriptor(
    name="ClassifierController",
    full_name="classifier.ClassifierController",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=172,
    serialized_end=265,
    methods=[
        _descriptor.MethodDescriptor(
            name="List",
            full_name="classifier.ClassifierController.List",
            index=0,
            containing_service=None,
            input_type=_CLASSIFIERLISTREQUEST,
            output_type=_CLASSIFIER,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_CLASSIFIERCONTROLLER)

DESCRIPTOR.services_by_name["ClassifierController"] = _CLASSIFIERCONTROLLER

# @@protoc_insertion_point(module_scope)
