# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import billing_pb2 as billing__pb2


class BillingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Summary = channel.unary_unary(
                '/billing.Billing/Summary',
                request_serializer=billing__pb2.BillingRequest.SerializeToString,
                response_deserializer=billing__pb2.BillingResponse.FromString,
                )


class BillingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Summary(self, request, context):
        """Get the total or active contacts in a time range
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Summary': grpc.unary_unary_rpc_method_handler(
                    servicer.Summary,
                    request_deserializer=billing__pb2.BillingRequest.FromString,
                    response_serializer=billing__pb2.BillingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'billing.Billing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Billing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Summary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/billing.Billing/Summary',
            billing__pb2.BillingRequest.SerializeToString,
            billing__pb2.BillingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
