# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from weni.user_grpc.grpc_gen import user_pb2 as weni_dot_user__grpc_dot_grpc__gen_dot_user__pb2


class UserControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/user.UserController/List',
                request_serializer=weni_dot_user__grpc_dot_grpc__gen_dot_user__pb2.UserListRequest.SerializeToString,
                response_deserializer=weni_dot_user__grpc_dot_grpc__gen_dot_user__pb2.Permission.FromString,
                )


class UserControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=weni_dot_user__grpc_dot_grpc__gen_dot_user__pb2.UserListRequest.FromString,
                    response_serializer=weni_dot_user__grpc_dot_grpc__gen_dot_user__pb2.Permission.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.UserController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/user.UserController/List',
            weni_dot_user__grpc_dot_grpc__gen_dot_user__pb2.UserListRequest.SerializeToString,
            weni_dot_user__grpc_dot_grpc__gen_dot_user__pb2.Permission.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
