# Generated by Django 3.2.9 on 2022-09-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tickets", "0025_remove_ticket_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketerQueue",
            fields=[
                (
                    "topic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="queue",
                        serialize=False,
                        to="tickets.topic",
                    ),
                ),
                (
                    "ticketer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queues",
                        to="tickets.ticketer",
                    ),
                ),
            ],
            options={
                "db_table": "internal_tickets_ticketerqueue",
            },
            bases=("tickets.topic",),
        ),
    ]
