# Generated by Django 3.2.15 on 2022-12-07 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0090_auto_20211209_2120'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Entity Created'), ('UPDATE', 'Updated Entity')], max_length=6)),
                ('entity', models.CharField(choices=[('FLOW', 'Flow Entity'), ('CHANNEL', 'Chanell Entity'), ('TRIGGER', 'Trigger Entity'), ('CAMPAIGN', 'Campaign Entity')], max_length=8)),
                ('entity_name', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateTimeField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orgs.org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internal_activities_recentactivity',
            },
        ),
    ]
