# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weni/org_grpc/grpc_gen/org.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='weni/org_grpc/grpc_gen/org.proto',
  package='org',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n weni/org_grpc/grpc_gen/org.proto\x12\x03org\x1a\x1bgoogle/protobuf/empty.proto\"H\n\x03Org\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\x19\n\x05users\x18\x04 \x03(\x0b\x32\n.org.Users\"[\n\x05Users\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x12\n\nfirst_name\x18\x04 \x01(\t\x12\x11\n\tlast_name\x18\x05 \x01(\t\"$\n\x0eOrgListRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\"C\n\x10OrgCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08timezone\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\"0\n\x11OrgDestroyRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"\x9f\x03\n\x10OrgUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x11\n\x04name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08timezone\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x64\x61te_format\x18\x05 \x01(\tH\x02\x88\x01\x01\x12\x11\n\x04plan\x18\x06 \x01(\tH\x03\x88\x01\x01\x12\x15\n\x08plan_end\x18\x07 \x01(\tH\x04\x88\x01\x01\x12\x12\n\x05\x62rand\x18\x08 \x01(\tH\x05\x88\x01\x01\x12\x14\n\x07is_anon\x18\t \x01(\x08H\x06\x88\x01\x01\x12\x1a\n\ris_multi_user\x18\n \x01(\x08H\x07\x88\x01\x01\x12\x19\n\x0cis_multi_org\x18\x0b \x01(\x08H\x08\x88\x01\x01\x12\x19\n\x0cis_suspended\x18\x0c \x01(\x08H\t\x88\x01\x01\x42\x07\n\x05_nameB\x0b\n\t_timezoneB\x0e\n\x0c_date_formatB\x07\n\x05_planB\x0b\n\t_plan_endB\x08\n\x06_brandB\n\n\x08_is_anonB\x10\n\x0e_is_multi_userB\x0f\n\r_is_multi_orgB\x0f\n\r_is_suspended2\xde\x01\n\rOrgController\x12)\n\x04List\x12\x13.org.OrgListRequest\x1a\x08.org.Org\"\x00\x30\x01\x12+\n\x06\x43reate\x12\x15.org.OrgCreateRequest\x1a\x08.org.Org\"\x00\x12\x38\n\x06Update\x12\x15.org.OrgUpdateRequest\x1a\x15.org.OrgUpdateRequest\"\x00\x12;\n\x07\x44\x65stroy\x12\x16.org.OrgDestroyRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ORG = _descriptor.Descriptor(
  name='Org',
  full_name='org.Org',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.Org.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='org.Org.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='org.Org.uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='users', full_name='org.Org.users', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=142,
)


_USERS = _descriptor.Descriptor(
  name='Users',
  full_name='org.Users',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.Users.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='org.Users.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='org.Users.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='org.Users.first_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='org.Users.last_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=235,
)


_ORGLISTREQUEST = _descriptor.Descriptor(
  name='OrgListRequest',
  full_name='org.OrgListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_email', full_name='org.OrgListRequest.user_email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=273,
)


_ORGCREATEREQUEST = _descriptor.Descriptor(
  name='OrgCreateRequest',
  full_name='org.OrgCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='org.OrgCreateRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timezone', full_name='org.OrgCreateRequest.timezone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='org.OrgCreateRequest.user_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=342,
)


_ORGDESTROYREQUEST = _descriptor.Descriptor(
  name='OrgDestroyRequest',
  full_name='org.OrgDestroyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.OrgDestroyRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='org.OrgDestroyRequest.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=392,
)


_ORGUPDATEREQUEST = _descriptor.Descriptor(
  name='OrgUpdateRequest',
  full_name='org.OrgUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='org.OrgUpdateRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='org.OrgUpdateRequest.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='org.OrgUpdateRequest.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timezone', full_name='org.OrgUpdateRequest.timezone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_format', full_name='org.OrgUpdateRequest.date_format', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='plan', full_name='org.OrgUpdateRequest.plan', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='plan_end', full_name='org.OrgUpdateRequest.plan_end', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brand', full_name='org.OrgUpdateRequest.brand', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_anon', full_name='org.OrgUpdateRequest.is_anon', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_multi_user', full_name='org.OrgUpdateRequest.is_multi_user', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_multi_org', full_name='org.OrgUpdateRequest.is_multi_org', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_suspended', full_name='org.OrgUpdateRequest.is_suspended', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_name', full_name='org.OrgUpdateRequest._name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_timezone', full_name='org.OrgUpdateRequest._timezone',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_date_format', full_name='org.OrgUpdateRequest._date_format',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_plan', full_name='org.OrgUpdateRequest._plan',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_plan_end', full_name='org.OrgUpdateRequest._plan_end',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_brand', full_name='org.OrgUpdateRequest._brand',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_anon', full_name='org.OrgUpdateRequest._is_anon',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_multi_user', full_name='org.OrgUpdateRequest._is_multi_user',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_multi_org', full_name='org.OrgUpdateRequest._is_multi_org',
      index=8, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_suspended', full_name='org.OrgUpdateRequest._is_suspended',
      index=9, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=395,
  serialized_end=810,
)

_ORG.fields_by_name['users'].message_type = _USERS
_ORGUPDATEREQUEST.oneofs_by_name['_name'].fields.append(
  _ORGUPDATEREQUEST.fields_by_name['name'])
_ORGUPDATEREQUEST.fields_by_name['name'].containing_oneof = _ORGUPDATEREQUEST.oneofs_by_name['_name']
_ORGUPDATEREQUEST.oneofs_by_name['_timezone'].fields.append(
  _ORGUPDATEREQUEST.fields_by_name['timezone'])
_ORGUPDATEREQUEST.fields_by_name['timezone'].containing_oneof = _ORGUPDATEREQUEST.oneofs_by_name['_timezone']
_ORGUPDATEREQUEST.oneofs_by_name['_date_format'].fields.append(
  _ORGUPDATEREQUEST.fields_by_name['date_format'])
_ORGUPDATEREQUEST.fields_by_name['date_format'].containing_oneof = _ORGUPDATEREQUEST.oneofs_by_name['_date_format']
_ORGUPDATEREQUEST.oneofs_by_name['_plan'].fields.append(
  _ORGUPDATEREQUEST.fields_by_name['plan'])
_ORGUPDATEREQUEST.fields_by_name['plan'].containing_oneof = _ORGUPDATEREQUEST.oneofs_by_name['_plan']
_ORGUPDATEREQUEST.oneofs_by_name['_plan_end'].fields.append(
  _ORGUPDATEREQUEST.fields_by_name['plan_end'])
_ORGUPDATEREQUEST.fields_by_name['plan_end'].containing_oneof = _ORGUPDATEREQUEST.oneofs_by_name['_plan_end']
_ORGUPDATEREQUEST.oneofs_by_name['_brand'].fields.append(
  _ORGUPDATEREQUEST.fields_by_name['brand'])
_ORGUPDATEREQUEST.fields_by_name['brand'].containing_oneof = _ORGUPDATEREQUEST.oneofs_by_name['_brand']
_ORGUPDATEREQUEST.oneofs_by_name['_is_anon'].fields.append(
  _ORGUPDATEREQUEST.fields_by_name['is_anon'])
_ORGUPDATEREQUEST.fields_by_name['is_anon'].containing_oneof = _ORGUPDATEREQUEST.oneofs_by_name['_is_anon']
_ORGUPDATEREQUEST.oneofs_by_name['_is_multi_user'].fields.append(
  _ORGUPDATEREQUEST.fields_by_name['is_multi_user'])
_ORGUPDATEREQUEST.fields_by_name['is_multi_user'].containing_oneof = _ORGUPDATEREQUEST.oneofs_by_name['_is_multi_user']
_ORGUPDATEREQUEST.oneofs_by_name['_is_multi_org'].fields.append(
  _ORGUPDATEREQUEST.fields_by_name['is_multi_org'])
_ORGUPDATEREQUEST.fields_by_name['is_multi_org'].containing_oneof = _ORGUPDATEREQUEST.oneofs_by_name['_is_multi_org']
_ORGUPDATEREQUEST.oneofs_by_name['_is_suspended'].fields.append(
  _ORGUPDATEREQUEST.fields_by_name['is_suspended'])
_ORGUPDATEREQUEST.fields_by_name['is_suspended'].containing_oneof = _ORGUPDATEREQUEST.oneofs_by_name['_is_suspended']
DESCRIPTOR.message_types_by_name['Org'] = _ORG
DESCRIPTOR.message_types_by_name['Users'] = _USERS
DESCRIPTOR.message_types_by_name['OrgListRequest'] = _ORGLISTREQUEST
DESCRIPTOR.message_types_by_name['OrgCreateRequest'] = _ORGCREATEREQUEST
DESCRIPTOR.message_types_by_name['OrgDestroyRequest'] = _ORGDESTROYREQUEST
DESCRIPTOR.message_types_by_name['OrgUpdateRequest'] = _ORGUPDATEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Org = _reflection.GeneratedProtocolMessageType('Org', (_message.Message,), {
  'DESCRIPTOR' : _ORG,
  '__module__' : 'weni.org_grpc.grpc_gen.org_pb2'
  # @@protoc_insertion_point(class_scope:org.Org)
  })
_sym_db.RegisterMessage(Org)

Users = _reflection.GeneratedProtocolMessageType('Users', (_message.Message,), {
  'DESCRIPTOR' : _USERS,
  '__module__' : 'weni.org_grpc.grpc_gen.org_pb2'
  # @@protoc_insertion_point(class_scope:org.Users)
  })
_sym_db.RegisterMessage(Users)

OrgListRequest = _reflection.GeneratedProtocolMessageType('OrgListRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORGLISTREQUEST,
  '__module__' : 'weni.org_grpc.grpc_gen.org_pb2'
  # @@protoc_insertion_point(class_scope:org.OrgListRequest)
  })
_sym_db.RegisterMessage(OrgListRequest)

OrgCreateRequest = _reflection.GeneratedProtocolMessageType('OrgCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORGCREATEREQUEST,
  '__module__' : 'weni.org_grpc.grpc_gen.org_pb2'
  # @@protoc_insertion_point(class_scope:org.OrgCreateRequest)
  })
_sym_db.RegisterMessage(OrgCreateRequest)

OrgDestroyRequest = _reflection.GeneratedProtocolMessageType('OrgDestroyRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORGDESTROYREQUEST,
  '__module__' : 'weni.org_grpc.grpc_gen.org_pb2'
  # @@protoc_insertion_point(class_scope:org.OrgDestroyRequest)
  })
_sym_db.RegisterMessage(OrgDestroyRequest)

OrgUpdateRequest = _reflection.GeneratedProtocolMessageType('OrgUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORGUPDATEREQUEST,
  '__module__' : 'weni.org_grpc.grpc_gen.org_pb2'
  # @@protoc_insertion_point(class_scope:org.OrgUpdateRequest)
  })
_sym_db.RegisterMessage(OrgUpdateRequest)



_ORGCONTROLLER = _descriptor.ServiceDescriptor(
  name='OrgController',
  full_name='org.OrgController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=813,
  serialized_end=1035,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='org.OrgController.List',
    index=0,
    containing_service=None,
    input_type=_ORGLISTREQUEST,
    output_type=_ORG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='org.OrgController.Create',
    index=1,
    containing_service=None,
    input_type=_ORGCREATEREQUEST,
    output_type=_ORG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='org.OrgController.Update',
    index=2,
    containing_service=None,
    input_type=_ORGUPDATEREQUEST,
    output_type=_ORGUPDATEREQUEST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='org.OrgController.Destroy',
    index=3,
    containing_service=None,
    input_type=_ORGDESTROYREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORGCONTROLLER)

DESCRIPTOR.services_by_name['OrgController'] = _ORGCONTROLLER

# @@protoc_insertion_point(module_scope)
