name: Build and Publish
on:
  push:
    tags: 
      - '*.*.*'
      - '*.*.*a*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set variables
      shell: bash
      run: |
        TAG="$( echo "${GITHUB_REF}" | cut -d'/' -f3 )"
        VERSION="${TAG}"
        echo "VERSION=${VERSION}" | tee -a "${GITHUB_ENV}"

    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install poetry
      uses: Gr1N/setup-poetry@v7

    - name: Update version in pyproject.toml
      shell: bash
      run: |
        sed -i 's;^version *=.*$;version = "'$VERSION'";g' pyproject.toml
    
    - name: Build package
      run: poetry build

    - name: Publish to pypi
      shell: bash
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish

    - name: Check out Kubernetes Manifests
        uses: actions/checkout@master
        with:
          ref: main
          repository: Ilhasoft/rapidpro
          token: "${{ secrets.DEVOPS_GITHUB_PERMANENT_TOKEN }}"
          path: ./rapidpro/
          
    - name: Update version on pip-requires.txt
      run: |
        sed -i 's;^weni-rp-apps@==.*$;weni-rp-apps@=='$VERSION';g' ./rapidpro/docker/pip-requires.txt

    - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: "${{ secrets.DEVOPS_GITHUB_PERMANENT_TOKEN }}"
          repository: Ilhasoft/rapidpro
          directory: ./rapidpro/
          branch: main
          message: "Update version of weni-rp-apps to ${{ env.VERSION }})"
