name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    env:
      python-version: '3.9.x'
      postgis-version: '3.1'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: ['14']

    # build:
    #   stage: build
    #   script:
    #     - git clone https://github.com/weni-ai/flows.git
    steps:
      - name: Checkout code from weni-ai/flows
        uses: actions/checkout@main
        with:
          repository: weni-ai/flows

      - name: Checkout code
        uses: actions/checkout@v3
        # incluir clone do flows da main

        # incluir c

      - name: Install PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: ${{ matrix.pg-version }}
          postgresql db: temba
          postgresql user: temba
          postgresql password: temba

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true

      - name: Initialize environment
        run: |
          poetry install
          ln -s ${{ github.workspace }}/settings.py.dev ${{ github.workspace }}/settings.py
          poetry run python manage.py migrate

      - name: Validate code syntax and unit tests
        run: |
          poetry run python contrib/code_check.py
          poetry run coverage xml

      - name: Mailroom log
        if: failure()
        run: cat mailroom.log

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: annotations,path,test_changes
          fail_ci_if_error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
